### ISSUE TITLE
Introduce a banished zone above the graveyard

### ISSUE THREAD

**Issue by scheibo** [acpennington/GoatController#146]
![](https://cdn.discordapp.com/attachments/864490203737620481/866799900883419156/Screen_Shot_2021-07-19_at_14.52.03.png)

![](https://cdn.discordapp.com/attachments/864490203737620481/866800948092076032/Screen_Shot_2021-07-19_at_14.57.22.png)

- add a banished zone above the graveyard and shift down the GY/Deck and Field Card Zone/Fusion Card zone by ~50% on each side to make room
- change the hand's location so that it fits in this new zone
- overlap the cards in the hand as necessary to fit in this reduced space like Dueling Book

TBD whether the hand should be allowed to overlap with the deck and or fusion deck at all. In Dueling Book the hand is not allowed to overlap the deck but can overlap the fusion deck to some extent

**Comment by acpennington** [comment]
Something that sage brought up was the fact that the fusion deck doesn't NEED to have any particular size or location. You could shrink the fusion deck vertically in order to make more room for the hand/banished, if we want to.
