### ISSUE TITLE
document recommended testing for most components

### ISSUE THREAD

**Issue by acpennington** [acpennington/GoatController#152]
For components that are changed frequently, we should document the edge cases that should be tested to ensure that updates do not introduce bugs.

**Comment by scheibo** [comment]
Love this, one other thing I think we can do (that we do at work) is add some description to the PR/commit message about what ways we tested. At work we add a `TESTED=...` tag to describe how we tested it (`TESTED=new unit tests` or `TESTED=tried scenario x y and z by hand`). See https://github.com/acpennington/GoatController/pull/158 for an example
