### ISSUE TITLE
Auto discard message doesn't account for cards which alter hand size limit

### ISSUE THREAD

**Issue by scheibo** [acpennington/GoatController#166]
Unless I'm mistaken, https://yugioh.fandom.com/wiki/Infinite_Cards (2003), https://yugioh.fandom.com/wiki/Enervating_Mist (2004)and https://yugioh.fandom.com/wiki/Hieroglyph_Lithograph (2005) all are legal in Goat format and fuck with the autodiscard reminders. These are kind of garbage tier niche cards so maybe the answer is "players should just ignore the discard prompts if these cards are in play"? I don't actually know if theres a clean way to handle this (the first 2 cards can kind of be detected by looking if theyre face up on the field, but perhaps theyre negated so who knows, and the fact that the last card is a lingering effect is kind of obnoxious and I think the only way to handle it would be to have a toggle in the UI that the player could hit to indicate they have resolved the effect? Or maybe a script, I don't know).

I had to create a new label for this that is the opposite of top priority because obviously this is so unlikely to be important, but I figured I'd file this bug just so we don't forget its actually a thing

**Comment by acpennington** [comment]
My plan was just to let the users figure out when they should ignore the discard reminder. Yes, we could try to add some hand size limit variable and adjust it with scripts, but do we really want to?

**Comment by scheibo** [comment]
I think we can maybe just add a toggle to right tools (or possibly some overflow menu accessible from right tools) that just is like "disable auto discard reminder". I feel if you dont have a way to disable it things would get confusing/annoying when you start playing these niche cards, and simply giving users the option to toggle it on/off is probably enough of a solution?

**Comment by acpennington** [comment]
Closing this since I honestly have no intention of ever doing this (seems like way more trouble than it's worth).
