### ISSUE TITLE
Scripts should be scoped to correct player and states

### ISSUE THREAD

**Issue by scheibo** [acpennington/GoatController#178]
Duo should only present the 'Random Discard' button to the villain (ie not the cards owner), Magical Merchant should only present the 'Mill Until' script to the player and only when it is actually on the field, not when its in the hand. This isn't too different from how prepopLP works.

**Comment by acpennington** [comment]
Agree, this is something that we need to do.

**Comment by scheibo** [comment]
I think `{hero: ..., villiain: ....}` is the obvious choice for scoping to players, and i think in all cases the scripts should only be active when the card in question is face up on the field. Are there more complex scenarios that I'm missing? Maybe some cards also have GY effects that need scripts?
