### ISSUE TITLE
Add shortcut to declare effect of a card

### ISSUE THREAD

**Issue by acpennington** [acpennington/GoatController#195]
If you click a card, and press "f", it should send a message to the chat that says "Activate the effect of [card name]."

**Comment by scheibo** [comment]
There should be a button for this as well (in right tools?), because shortcuts are not discoverable and dont work on mobile

**Comment by acpennington** [comment]
Yeah, I guess that makes sense. I don't want right tools to have a million different buttons, but this should be fine.

**Comment by acpennington** [comment]
It might even make sense to make the button in the chat instead of in right tools. It's really a chat shortcut, not a game shortcut.

**Comment by scheibo** [comment]
i feel you declare effects even more than you add counters. i also feel the add counter tool can be condensed to one row instead of 2

**Comment by acpennington** [comment]
I wanted to put counters on one row, but it didn't work too well on smaller screens. I'll give it a second look.

**Comment by scheibo** [comment]
![Screen Shot 2021-07-28 at 14 37 37](https://user-images.githubusercontent.com/117249/127399579-cca14ded-4a82-4c3d-9df0-c916f969dc17.png)
My suggestion is just a "Counters" label with a `+` button on one side and a `-` on the other. Either of the counters buttons would be just as easy/difficult to hit as the current Life Points button.

But yeah, i'd also just add a 'Declare Effect' button under that condensed counters button. Its chat specific but also highly used (i mean, even DB has implemented it), so i think its worth the real estate in the right pane
