### ISSUE TITLE
Print hand in chat when revealed

### ISSUE THREAD

**Issue by acpennington** [acpennington/GoatController#235]
When a user reveals their hand, we should just print a list of the cards in the chat. This should not be difficult.

**Comment by scheibo** [comment]
So printing the hand on initial reveal is probably not that hard, but one complication is that subsequent draws when the hand is being revealed should also be logged. This might be too much effort and so I imagine we won't bother and instead will let the user cover that more niche case?

**Comment by acpennington** [comment]
Yeah realize that the main motive for this ticket is Trap Dustshoot. The odds of a hand being revealed for multiple turns is slim to none.

**Comment by scheibo** [comment]
Are you suggesting Ceremonial Bell is not meta???
