### ISSUE TITLE
Add script ability for players to generically look in their deck

### ISSUE THREAD

**Issue by scheibo** [acpennington/GoatController#254]
Abyssal/Dark Designator as well as stuff like Arsenal Robber etc likely needs to allow the opponent to view the players deck (in order to confirm), and Vampire Lord requires a player be able to look in their deck pretty much generically (though alternatively in the Vampire Lord case there could be a 'Search Monster', 'Search Monster' and 'Search Trap' script buttons - unclear whether this isn't just more work).

**Comment by acpennington** [comment]
Looking at your own deck generically should not be an issue to implement. There should never be any circumstance in which you are looking at your entire opponent's deck. I think there are a few cards that allow you to view the top X cards of your opponent's deck though.

**Comment by scheibo** [comment]
Implementing eg. the designator cards seems quite difficult otherwise (eg. for Abyssal Designator you would need a type and attribute dropdown probably?). Alternatively is the idea that you just need to trust your opponent and rely on being able to go back over a replay or something the approach?

**Comment by acpennington** [comment]
There is not exactly a clean way to implement Abyssal Designator, but for now we can just let the opponent view their entire deck and trust them not to lie if they say that they have no legal targets. Given the lack of competitive viability of this card, coming up with a better solution will be bottom priority.

**Comment by acpennington** [comment]
Leave params blank for generic search.
