### ISSUE TITLE
Card movement displays the art label

### ISSUE THREAD

**Issue by acpennington** [acpennington/GoatController#337]
The server includes the art with the card. E.g. "Dark Magician|3"

This shouldn't happen.

**Comment by scheibo** [comment]
Saw this on stream today when attacking GoatToken2

**Comment by acpennington** [comment]
Yeah, I did too. Probably would need to test more to figure out what are the exact circumstances that do/do not trigger this bug.

**Comment by scheibo** [comment]
Did more thorough testing: this effects all server actions which display card names (`SendAttack`, `SendCardMove`, `SendCounters`, `SendPosChange`) which makes sense, but **only effects token monsters**. All of these with like Dark Magician or Dark Magician Girl alt art work fine.
