### ISSUE TITLE
Investigate Indexed Database API

### ISSUE THREAD

**Issue by acpennington** [acpennington/GoatController#91]
We should experiment with using the Indexed Database API to store user data rather than the Web Storage API. We don't run into problems with storage limits that way. It may also be easier to work with.

**Comment by acpennington** [comment]
Should probably use Dexie: https://dexie.org/

**Comment by scheibo** [comment]
IDB is actually rather miserable to work with. Does #145 obviate the need for this? I don't think we should be storing anything too critical/large in web storage anyway?

**Comment by acpennington** [comment]
If you say it sucks, I'll take your word for it. I was considering retrieving all of the user's decks and putting them in web storage when they login (rather than hitting the server everytime you want to retrieve one of your decks). Depending on how many decks they had, I was concerned that it might hit WebStorage limits.

**Comment by scheibo** [comment]
If you're just using it as a cache that shouldn't really be a problem. PS actually stores a player's teams exclusively in local storage and a Pokémon team is roughly the same size in bytes more or less as a deck I think. (6 pokemon names 6 ability names, 6 items, 6x4 move names on its own is already close to 40 card names, and thats not including EVs/IVs etc). Players have upwards of thousands of teams and start running into browser storage limits, but I a) dont think YGO players will have that many decks and b) PS power users are fine working around the limitations (though i think PS is still dumb and should be storing the teams on its server as well, so Im glad you plan to with goatduels.com)

You might not want to fetch all decks at login but instead fetch just the deck names and then fetch decks on demand but cache the decks that are fetched such that they are not all sent over at once. Bandwidth is always the name of the game (see https://blog.cloudflare.com/aws-egregious-egress/ for example which just was published today), and I think if people have a lot of decks thats potentially a big payload with data they might not even use.

EDIT: actually, you should sent over deck names and a hash of the deck list from the server on login, and then only sync the decks where the hash changes. The hash lets you know which decks the client and the server are already in sync on

**Comment by acpennington** [comment]
Probably won't need to do this. Closed.
