### ISSUE TITLE
Seperate prepopLP into prepopHeroLP and prepopVillLP

### ISSUE THREAD

**Issue by acpennington** [acpennington/GoatController#92]
This will be particularly useful for cards like Poison of the Old Man.

**Comment by scheibo** [comment]
Stealing because I don't think this is super high priority and looks straightforward :)

**Comment by scheibo** [comment]
I think its cleaner to change `prepopLP`'s type from `number | "half"` to `number | "half" | {hero?: number, villain?: number}` as opposed to splitting the field into multiple fields (you just need to add a `typeof prepopLP === 'object'` check when actually utilizing the value in `StandardTools.js`. However, I'm not entirely sure how PofOM is going to work given the user has a choice there. Do we want to just make the (logical) assumption that if both `hero` and `villain` options are present link in this case youre going to want to choose burning the villain? IE

```js
   render() {
      const { classes, prepopLP, prepopLPvalue, player, resetSolo, lifepoints } = this.props;

      const { name, solo } = player;
      const { LPmode, dontSwap } = this.state;

      const LPinputField = document.getElementById(LPinput);
      if (LPinputField && prepopLPvalue) {
         if (dontSwap) this.setState({ dontSwap: false });
         else {
            if (typeof prepopLP === 'object') {
               if (prepopLP.hero && preprop.villain) {
                  // TODO assume we want to apply villain
               } else if (preprop.villain) {
                  // TODO apply to villain
               } else if (preprop.hero) {
                  // TODO apply to hero
               }
            } else if (prepopLPvalue === "half") {
               LPinputField.value = Math.floor(lifepoints.hero / 2);
               if (LPmode !== -1) this.swapLPmode();
            } else {
               LPinputField.value = Math.abs(prepopLPvalue);
               if (LPmode * prepopLPvalue < 0) this.swapLPmode();
            }
         }
      }
```

**Comment by acpennington** [comment]
I think your approach of changing prepopLP into an object makes much more sense.

I think you misunderstand my intention here slightly though. In the case of Poison of the Old Man, of course we'd have prepopLP: { hero: 1200, villain: -800 }. Then if the hero clicks the card, it will autofill +1200. If the villain clicks the card, it will autofill -800. The idea is that the person who activated the card would still need to declare which effect they are using, but in either case, the affected player would be able to prepop.

Cards like Snatch Steal on the other hand would have prepopLP: { villain: 1000 }. If the hero clicks on their Snatch Steal, it will do nothing. But if the villain clicks on Snatch Steal, it will autofill +1000.

Note: Hero and villain in this context mean "the player who controls the card" and "the player who does not control the card," respectively.
